language: python
python:
  - '3.7'
install:
  - pip install --upgrade -e . -r ./requirements/dev
script:
  - export BOTO_CONFIG=/dev/null
  - pytest --cov=fastq_demux tests/
after_success:
  - codecov
notifications:
  email: false
